---
- name: Add Digital Ocean metrics agent package signing key
  apt_key:
    url: https://repos.sonar.digitalocean.com/sonar-agent.asc
    state: present
  tags: do-agent

- name: Add repo for DO metrics agent
  apt_repository:
    repo: deb https://repos.sonar.digitalocean.com/apt main main
    state: present
    filename: 'digitalocean-agent'
  tags: do-agent

- name: Install DO metrics agent
  apt:
    name: do-agent
    update_cache: yes
    state: latest
  tags: do-agent

- name: Start and enable DO metrics agent
  service:
    name: do-agent
    state: started
    enabled: yes
  tags: do-agent
